#!/bin/bash

#set -e

#echo "REPO=$BUILDKITE_REPO"

export UNITY_BUILDER_EDITOR_VERSION=$(grep "^m_EditorVersion:" "$UNITY_BUILDER_PROJECT_DIR/ProjectSettings/ProjectVersion.txt" | cut -d " " -f2)

echo "UNITY_BUILDER_EDITOR_VERSION=$UNITY_BUILDER_EDITOR_VERSION"

